---
name: Social Interaction

on:
  issues: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome aboard! We value your input and will address your issue soon."
          pr-message: "Great job on your first PR! Your contribution helps improve the project."
